### ISSUE TITLE
Using data from SCD30 to trigger relays

### ISSUE THREAD

**Issue by WRCHAP** [en0b/rPi-Pico-micropython-Simple-SCD30#2]
Many thanks for the script - works out of the box! I have ordered a book on MicroPython from Elector to gain more insight into Micropython. While I have been able to trigger a relay using the built-in temperature sensor on the Pi Pico, my attempts to do the same with the SCD30 sensor data has not worked. None of the information that I have found while researching has provided any guidance on the control side of such a project.

**Comment by en0b** [comment]
Glad to hear that my script helped you to get the SCD30 up and running. Good Luck with your project!
